podTemplate(label: 'Pod-temp-ljw', containers: [
    containerTemplate(name: 'checkov', image: 'bridgecrew/checkov:latest', command: 'cat', ttyEnabled: true, resourceRequestMemory: '512Mi', resourceRequestCpu: '512m')
], 
    volumes: [
        hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock')
    ]
) {
    node('Pod-temp-ljw') {
        withEnv([
            'PRISMA_API_URL=https://api.jp.prismacloud.io',
            'REPO_ID=78won96/GCP-Project-ljw',
            'BRANCH=main'
        ]) {
            stage('Checkout') {
                git branch: 'main', url: 'https://github.com/78won96/GCP-Project-ljw.git'
                stash includes: '**/*', name: 'source'
            }
            
            stage('Checkov') {
		 withCredentials([string(credentialsId: 'PC_USER', variable: 'prismauser'),string(credentialsId: 'PC_PASSWORD', variable: 'prismapwd')]) {
                	container('checkov') {
                    		unstash 'source'
                    			sh '''
                      				checkov -d . --use-enforcement-rules -o cli -o junitxml \ #withEnv에서 변수 지정시 checkov config에서 해당 변수명으로 자동 지정 됨
                        			--prisma-api-url ${PRISMA_API_URL} \
                        			--output-file-path console,results.xml \
                        			--bc-api-key ${prismauser}::${prismapwd} \
                        			--repo-id $REPO_ID --branch $BRANCH
                    				'''
                    			junit skipPublishingChecks: true, testResults: 'results.xml'
                }
            }
        }
    }
}
}
