pipeline {
    agent any
    
    stages {
        
        stage('github-clone') {
            steps {
                git branch: 'main', credentialsId: 'jenkins-token', url: 'https://github.com/78won96/GCP-Project-ljw.git'
            }
        }
        
   		// stage...
   	}
}
