
label = "Pod-temp-ljw"

podTemplate(label: label, containers: [

    containerTemplate(name: "gcloud", image: "google/cloud-sdk:alpine", command: "cat", ttyEnabled: true, alwaysPullImage: true, resourceRequestCpu: '10m'),

    containerTemplate(name: "ubuntu", image: "ubuntu", command: "cat", ttyEnabled: true, alwaysPullImage: true, resourceRequestCpu: '10m'),

],

    volumes: [

        hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock"),

    ],

) 
{

    node(label) {

        stage('Docker') {

            container("gcloud") {

                    withCredentials([file(credentialsId: 'google-id', variable: 'GOOGLE_AUTH')]) {

                    sh '''
                    gcloud auth activate-service-account --key-file="$GOOGLE_AUTH"
                    gcloud --quiet auth configure-docker
                    gcloud --quiet auth configure-docker asia-northeast3-docker.pkg.dev
                    docker pull gcr.io/google-samples/hello-app:1.0
                    docker images
                '''

                }
            }
        }
    }
}